services:
  app:
    build: .
    container_name: yolo_platform_api
    restart: unless-stopped
    shm_size: "2gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    ports:
      - "58000:8000"
    volumes:
      - ./models:/data/models
      - ./runtime:/app/runtime
      - ./webui:/app/webui
    environment:
      - MODELS_DIR=/data/models
